### PR TITLE
Updated FlashLight Section

### PR DESCRIPTION
**Pull request by AndroiableDroid**
Some Devices doesn't Supports "/sys/class/leds/led:torch_" so in mine it "/sys/class/leds/torch-light" 
 * respectively Added One more Condition to check this path

### CODE REVIEW

**Comment by AndroiableDroid** [comment]
Sir plz merge this request.

**Comment by danparidae** [comment]
did you test it? it works on both paths?

**Comment by AndroiableDroid** [comment]
Yes sir i have tested it is working on both paths

**Comment by AndroiableDroid** [comment]
sir plz merge it

**Comment by AndroiableDroid** [comment]
can i  have my device official

**Pull request merged**
