### PR TITLE
Update tr.xml

### PR DESCRIPTION
**Pull request by ghost**
Hello, I've translated it the official twrp and this. I have a desire for it. In the twrp settings section, there are too many spaces between the tick box and the text. Can this be reduced? I wanted to write short words, but they do not make sense. I hope you will consider. Thanks. Have a nice day.
please look at the picture: https://i.hizliresim.com/lO8glX.png

### CODE REVIEW

**Review by danparidae — CHANGES_REQUESTED** [review]
sorry but for me it doesn't look properly. you have removed a bunch of strings or doubled some of them. Also don't use capital letters for whole words and test it (compile, run and see if everything is fine) before pushing another pull request. This one is not going to be merged

**Comment by ghost** [comment]
I am sorry too. Actually I have been testing for days with image studio for android. I did not capital letters according to my wishes. According to my testing, only the settings part does not fit. I think everything was in the way, I'm sorry to bother you.

**Comment by ghost** [comment]
Hello. Can you tell me exactly my mistakes?
Please write my mistakes in detail, it is not a sloppy translation. I never sent a request without testing. Thanks.

**Comment by ghost** [comment]
Dear @dadi11 , I made the translation from the original English version of redwolf's strings. There are a lot of big letters in it, so I made it big. Also I deleted some lines, because these strings do not exist in your recovery's english strings. How can I do the translation in this case? Thanks.

**Pull request closed without merging**
